package WrenchDb.DAL.Entities;
// Generated 29-ott-2013 7.38.52 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WbdProperty generated by hbm2java
 */
@Entity
@Table(name="wbd_property"
    ,schema="public"
    , uniqueConstraints = @UniqueConstraint(columnNames={"property_name", "entity_id"}) 
)
public class WbdProperty  implements java.io.Serializable {


     private long propertyId;
     private WdbEntity wdbEntity;
     private WdbPropertyType wdbPropertyType;
     private long propertyName;
     private String propertyLabel;
     private Long isInlist;
     private Boolean isInnew;
     private Boolean isInedit;
     private Long isIndetail;
     private String configData;
     private Integer width;

    public WbdProperty() {
    }

	
    public WbdProperty(long propertyId, WdbEntity wdbEntity, long propertyName) {
        this.propertyId = propertyId;
        this.wdbEntity = wdbEntity;
        this.propertyName = propertyName;
    }
    public WbdProperty(long propertyId, WdbEntity wdbEntity, WdbPropertyType wdbPropertyType, long propertyName, String propertyLabel, Long isInlist, Boolean isInnew, Boolean isInedit, Long isIndetail, String configData, Integer width) {
       this.propertyId = propertyId;
       this.wdbEntity = wdbEntity;
       this.wdbPropertyType = wdbPropertyType;
       this.propertyName = propertyName;
       this.propertyLabel = propertyLabel;
       this.isInlist = isInlist;
       this.isInnew = isInnew;
       this.isInedit = isInedit;
       this.isIndetail = isIndetail;
       this.configData = configData;
       this.width = width;
    }
   
     @Id 
    
    @Column(name="property_id", unique=true, nullable=false)
       @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(long propertyId) {
        this.propertyId = propertyId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entity_id", nullable=false)
    public WdbEntity getWdbEntity() {
        return this.wdbEntity;
    }
    
    public void setWdbEntity(WdbEntity wdbEntity) {
        this.wdbEntity = wdbEntity;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="property_type")
    public WdbPropertyType getWdbPropertyType() {
        return this.wdbPropertyType;
    }
    
    public void setWdbPropertyType(WdbPropertyType wdbPropertyType) {
        this.wdbPropertyType = wdbPropertyType;
    }
    
    @Column(name="property_name", nullable=false)
    public long getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(long propertyName) {
        this.propertyName = propertyName;
    }
    
    @Column(name="property_label", length=200)
    public String getPropertyLabel() {
        return this.propertyLabel;
    }
    
    public void setPropertyLabel(String propertyLabel) {
        this.propertyLabel = propertyLabel;
    }
    
    @Column(name="is_inlist")
    public Long getIsInlist() {
        return this.isInlist;
    }
    
    public void setIsInlist(Long isInlist) {
        this.isInlist = isInlist;
    }
    
    @Column(name="is_innew")
    public Boolean getIsInnew() {
        return this.isInnew;
    }
    
    public void setIsInnew(Boolean isInnew) {
        this.isInnew = isInnew;
    }
    
    @Column(name="is_inedit")
    public Boolean getIsInedit() {
        return this.isInedit;
    }
    
    public void setIsInedit(Boolean isInedit) {
        this.isInedit = isInedit;
    }
    
    @Column(name="is_indetail")
    public Long getIsIndetail() {
        return this.isIndetail;
    }
    
    public void setIsIndetail(Long isIndetail) {
        this.isIndetail = isIndetail;
    }
    
    @Column(name="config_data", length=8000)
    public String getConfigData() {
        return this.configData;
    }
    
    public void setConfigData(String configData) {
        this.configData = configData;
    }
    
    @Column(name="width")
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }




}


