package WrenchDb.DAL.Entities;
// Generated 27-ott-2013 17.28.51 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * WdbApplication generated by hbm2java
 */
@Entity
@Table(name="wdb_application"
    ,schema="public"
    , uniqueConstraints = {@UniqueConstraint(columnNames="application_hostname"), @UniqueConstraint(columnNames="application_name")} 
)
public class WdbApplication  implements java.io.Serializable {


     private long applicationId;
     private String applicationName;
     private long applicationHostname;
     private Set<WdbSettings> wdbSettingses = new HashSet<WdbSettings>(0);
     private Set<WdbChangescript> wdbChangescripts = new HashSet<WdbChangescript>(0);
     private Set<WdbSitemap> wdbSitemaps = new HashSet<WdbSitemap>(0);
     private Set<WdbEntity> wdbEntities = new HashSet<WdbEntity>(0);

    public WdbApplication() {
    }

	
    public WdbApplication(long applicationId, String applicationName, long applicationHostname) {
        this.applicationId = applicationId;
        this.applicationName = applicationName;
        this.applicationHostname = applicationHostname;
    }
    public WdbApplication(long applicationId, String applicationName, long applicationHostname, Set<WdbSettings> wdbSettingses, Set<WdbChangescript> wdbChangescripts, Set<WdbSitemap> wdbSitemaps, Set<WdbEntity> wdbEntities) {
       this.applicationId = applicationId;
       this.applicationName = applicationName;
       this.applicationHostname = applicationHostname;
       this.wdbSettingses = wdbSettingses;
       this.wdbChangescripts = wdbChangescripts;
       this.wdbSitemaps = wdbSitemaps;
       this.wdbEntities = wdbEntities;
    }
   
     @Id 
    
    @Column(name="application_id", unique=true, nullable=false)
    public long getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(long applicationId) {
        this.applicationId = applicationId;
    }
    
    @Column(name="application_name", unique=true, nullable=false, length=200)
    public String getApplicationName() {
        return this.applicationName;
    }
    
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }
    
    @Column(name="application_hostname", unique=true, nullable=false)
    public long getApplicationHostname() {
        return this.applicationHostname;
    }
    
    public void setApplicationHostname(long applicationHostname) {
        this.applicationHostname = applicationHostname;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="wdbApplication")
    public Set<WdbSettings> getWdbSettingses() {
        return this.wdbSettingses;
    }
    
    public void setWdbSettingses(Set<WdbSettings> wdbSettingses) {
        this.wdbSettingses = wdbSettingses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="wdbApplication")
    public Set<WdbChangescript> getWdbChangescripts() {
        return this.wdbChangescripts;
    }
    
    public void setWdbChangescripts(Set<WdbChangescript> wdbChangescripts) {
        this.wdbChangescripts = wdbChangescripts;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="wdbApplication")
    public Set<WdbSitemap> getWdbSitemaps() {
        return this.wdbSitemaps;
    }
    
    public void setWdbSitemaps(Set<WdbSitemap> wdbSitemaps) {
        this.wdbSitemaps = wdbSitemaps;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="wdbApplication")
    public Set<WdbEntity> getWdbEntities() {
        return this.wdbEntities;
    }
    
    public void setWdbEntities(Set<WdbEntity> wdbEntities) {
        this.wdbEntities = wdbEntities;
    }




}


