package WrenchDb.DAL.Entities;
// Generated 29-ott-2013 7.38.52 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WdbChangescript generated by hbm2java
 */
@Entity
@Table(name="wdb_changescript"
    ,schema="public"
)
public class WdbChangescript  implements java.io.Serializable {


     private long changescriptId;
     private WdbApplication wdbApplication;
     private String changescriptDesc;
     private Serializable changescriptSql;
     private boolean isDeployed;

    public WdbChangescript() {
    }

	
    public WdbChangescript(long changescriptId, Serializable changescriptSql, boolean isDeployed) {
        this.changescriptId = changescriptId;
        this.changescriptSql = changescriptSql;
        this.isDeployed = isDeployed;
    }
    public WdbChangescript(long changescriptId, WdbApplication wdbApplication, String changescriptDesc, Serializable changescriptSql, boolean isDeployed) {
       this.changescriptId = changescriptId;
       this.wdbApplication = wdbApplication;
       this.changescriptDesc = changescriptDesc;
       this.changescriptSql = changescriptSql;
       this.isDeployed = isDeployed;
    }
   
     @Id 
    
    @Column(name="changescript_id", unique=true, nullable=false)
       @GeneratedValue(strategy = GenerationType.IDENTITY)
    public long getChangescriptId() {
        return this.changescriptId;
    }
    
    public void setChangescriptId(long changescriptId) {
        this.changescriptId = changescriptId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="application_id")
    public WdbApplication getWdbApplication() {
        return this.wdbApplication;
    }
    
    public void setWdbApplication(WdbApplication wdbApplication) {
        this.wdbApplication = wdbApplication;
    }
    
    @Column(name="changescript_desc", length=200)
    public String getChangescriptDesc() {
        return this.changescriptDesc;
    }
    
    public void setChangescriptDesc(String changescriptDesc) {
        this.changescriptDesc = changescriptDesc;
    }
    
    @Column(name="changescript_sql", nullable=false)
    public Serializable getChangescriptSql() {
        return this.changescriptSql;
    }
    
    public void setChangescriptSql(Serializable changescriptSql) {
        this.changescriptSql = changescriptSql;
    }
    
    @Column(name="is_deployed", nullable=false)
    public boolean isIsDeployed() {
        return this.isDeployed;
    }
    
    public void setIsDeployed(boolean isDeployed) {
        this.isDeployed = isDeployed;
    }




}


