package WrenchDb.DAL.Entities;
// Generated 8-dic-2013 14.59.34 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * WdbProperty generated by hbm2java
 */
@Entity
@Table(name="wdb_property"
    ,schema="public"
)
public class WdbProperty  implements java.io.Serializable {


     private long propertyId;
     private WdbEntity wdbEntity;
     private WdbPropertyType wdbPropertyType;
     private String propertyLabel;
     private String configData;
     private Integer width;
     private Boolean isInnew;
     private Boolean isInedit;
     private Boolean isInview;
     private Boolean isInlist;
     private String propertyName;

    public WdbProperty() {
    }

	
    public WdbProperty(long propertyId, WdbEntity wdbEntity, String propertyName) {
        this.propertyId = propertyId;
        this.wdbEntity = wdbEntity;
        this.propertyName = propertyName;
    }
    public WdbProperty(long propertyId, WdbEntity wdbEntity, WdbPropertyType wdbPropertyType, String propertyLabel, String configData, Integer width, Boolean isInnew, Boolean isInedit, Boolean isInview, Boolean isInlist, String propertyName) {
       this.propertyId = propertyId;
       this.wdbEntity = wdbEntity;
       this.wdbPropertyType = wdbPropertyType;
       this.propertyLabel = propertyLabel;
       this.configData = configData;
       this.width = width;
       this.isInnew = isInnew;
       this.isInedit = isInedit;
       this.isInview = isInview;
       this.isInlist = isInlist;
       this.propertyName = propertyName;
    }
   
     @Id 
          @Generated(GenerationTime.INSERT)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="property_id", unique=true, nullable=false)
    public long getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(long propertyId) {
        this.propertyId = propertyId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entity_id", nullable=false)
    public WdbEntity getWdbEntity() {
        return this.wdbEntity;
    }
    
    public void setWdbEntity(WdbEntity wdbEntity) {
        this.wdbEntity = wdbEntity;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="property_type")
    public WdbPropertyType getWdbPropertyType() {
        return this.wdbPropertyType;
    }
    
    public void setWdbPropertyType(WdbPropertyType wdbPropertyType) {
        this.wdbPropertyType = wdbPropertyType;
    }
    
    @Column(name="property_label", length=200)
    public String getPropertyLabel() {
        return this.propertyLabel;
    }
    
    public void setPropertyLabel(String propertyLabel) {
        this.propertyLabel = propertyLabel;
    }
    
    @Column(name="config_data", length=8000)
    public String getConfigData() {
        return this.configData;
    }
    
    public void setConfigData(String configData) {
        this.configData = configData;
    }
    
    @Column(name="width")
    public Integer getWidth() {
        return this.width;
    }
    
    public void setWidth(Integer width) {
        this.width = width;
    }
    
    @Column(name="is_innew")
    public Boolean getIsInnew() {
        return this.isInnew;
    }
    
    public void setIsInnew(Boolean isInnew) {
        this.isInnew = isInnew;
    }
    
    @Column(name="is_inedit")
    public Boolean getIsInedit() {
        return this.isInedit;
    }
    
    public void setIsInedit(Boolean isInedit) {
        this.isInedit = isInedit;
    }
    
    @Column(name="is_inview")
    public Boolean getIsInview() {
        return this.isInview;
    }
    
    public void setIsInview(Boolean isInview) {
        this.isInview = isInview;
    }
    
    @Column(name="is_inlist")
    public Boolean getIsInlist() {
        return this.isInlist;
    }
    
    public void setIsInlist(Boolean isInlist) {
        this.isInlist = isInlist;
    }
    
    @Column(name="property_name", nullable=false, length=300)
    public String getPropertyName() {
        return this.propertyName;
    }
    
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }




}


