package WrenchDb.DAL.Entities;
// Generated 27-ott-2013 17.28.51 by Hibernate Tools 3.2.1.GA


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WdbPropertyType generated by hbm2java
 */
@Entity
@Table(name="wdb_property_type"
    ,schema="public"
)
public class WdbPropertyType  implements java.io.Serializable {


     private long propertyType;
     private Serializable propertyTypeName;
     private Serializable propertyTypeDesc;
     private Set<WbdProperty> wbdProperties = new HashSet<WbdProperty>(0);

    public WdbPropertyType() {
    }

	
    public WdbPropertyType(long propertyType) {
        this.propertyType = propertyType;
    }
    public WdbPropertyType(long propertyType, Serializable propertyTypeName, Serializable propertyTypeDesc, Set<WbdProperty> wbdProperties) {
       this.propertyType = propertyType;
       this.propertyTypeName = propertyTypeName;
       this.propertyTypeDesc = propertyTypeDesc;
       this.wbdProperties = wbdProperties;
    }
   
     @Id 
    
    @Column(name="property_type", unique=true, nullable=false)
    public long getPropertyType() {
        return this.propertyType;
    }
    
    public void setPropertyType(long propertyType) {
        this.propertyType = propertyType;
    }
    
    @Column(name="property_type_name")
    public Serializable getPropertyTypeName() {
        return this.propertyTypeName;
    }
    
    public void setPropertyTypeName(Serializable propertyTypeName) {
        this.propertyTypeName = propertyTypeName;
    }
    
    @Column(name="property_type_desc")
    public Serializable getPropertyTypeDesc() {
        return this.propertyTypeDesc;
    }
    
    public void setPropertyTypeDesc(Serializable propertyTypeDesc) {
        this.propertyTypeDesc = propertyTypeDesc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="wdbPropertyType")
    public Set<WbdProperty> getWbdProperties() {
        return this.wbdProperties;
    }
    
    public void setWbdProperties(Set<WbdProperty> wbdProperties) {
        this.wbdProperties = wbdProperties;
    }




}


