package WrenchDb.DAL.Entities;
// Generated 5-dic-2013 18.23.45 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * WdbPropertyType generated by hbm2java
 */
@Entity
@Table(name="wdb_property_type"
    ,schema="public"
)
public class WdbPropertyType  implements java.io.Serializable {


     private long propertyType;
     private String propertyTypeName;
     private String propertyTypeDesc;
     private Set<WdbProperty> wdbProperties = new HashSet<WdbProperty>(0);

    public WdbPropertyType() {
    }

	
    public WdbPropertyType(long propertyType) {
        this.propertyType = propertyType;
    }
    public WdbPropertyType(long propertyType, String propertyTypeName, String propertyTypeDesc, Set<WdbProperty> wdbProperties) {
       this.propertyType = propertyType;
       this.propertyTypeName = propertyTypeName;
       this.propertyTypeDesc = propertyTypeDesc;
       this.wdbProperties = wdbProperties;
    }
   
     @Id 
      @Generated(GenerationTime.INSERT)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="property_type", unique=true, nullable=false)
    public long getPropertyType() {
        return this.propertyType;
    }
    
    public void setPropertyType(long propertyType) {
        this.propertyType = propertyType;
    }
    
    @Column(name="property_type_name")
    public String getPropertyTypeName() {
        return this.propertyTypeName;
    }
    
    public void setPropertyTypeName(String propertyTypeName) {
        this.propertyTypeName = propertyTypeName;
    }
    
    @Column(name="property_type_desc")
    public String getPropertyTypeDesc() {
        return this.propertyTypeDesc;
    }
    
    public void setPropertyTypeDesc(String propertyTypeDesc) {
        this.propertyTypeDesc = propertyTypeDesc;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="wdbPropertyType")
    public Set<WdbProperty> getWdbProperties() {
        return this.wdbProperties;
    }
    
    public void setWdbProperties(Set<WdbProperty> wdbProperties) {
        this.wdbProperties = wdbProperties;
    }




}


