package WrenchDb.DAL.Entities;
// Generated 8-dic-2013 14.59.34 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * WdbRelease generated by hbm2java
 */
@Entity
@Table(name="wdb_release"
    ,schema="public"
)
public class WdbRelease  implements java.io.Serializable {


     private long wdbReleaseId;
     private WdbApplication wdbApplication;
     private long releaseVersion;
     private String releaseFullversion;
     private String releaseMemocode;
     private long databaseVersion;
     private Date releasedOn;

    public WdbRelease() {
    }

	
    public WdbRelease(long wdbReleaseId, long releaseVersion, String releaseFullversion, String releaseMemocode, long databaseVersion, Date releasedOn) {
        this.wdbReleaseId = wdbReleaseId;
        this.releaseVersion = releaseVersion;
        this.releaseFullversion = releaseFullversion;
        this.releaseMemocode = releaseMemocode;
        this.databaseVersion = databaseVersion;
        this.releasedOn = releasedOn;
    }
    public WdbRelease(long wdbReleaseId, WdbApplication wdbApplication, long releaseVersion, String releaseFullversion, String releaseMemocode, long databaseVersion, Date releasedOn) {
       this.wdbReleaseId = wdbReleaseId;
       this.wdbApplication = wdbApplication;
       this.releaseVersion = releaseVersion;
       this.releaseFullversion = releaseFullversion;
       this.releaseMemocode = releaseMemocode;
       this.databaseVersion = databaseVersion;
       this.releasedOn = releasedOn;
    }
   
     @Id 
          @Generated(GenerationTime.INSERT)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="wdb_release_id", unique=true, nullable=false)
    public long getWdbReleaseId() {
        return this.wdbReleaseId;
    }
    
    public void setWdbReleaseId(long wdbReleaseId) {
        this.wdbReleaseId = wdbReleaseId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="application_id")
    public WdbApplication getWdbApplication() {
        return this.wdbApplication;
    }
    
    public void setWdbApplication(WdbApplication wdbApplication) {
        this.wdbApplication = wdbApplication;
    }
    
    @Column(name="release_version", nullable=false)
    public long getReleaseVersion() {
        return this.releaseVersion;
    }
    
    public void setReleaseVersion(long releaseVersion) {
        this.releaseVersion = releaseVersion;
    }
    
    @Column(name="release_fullversion", nullable=false, length=100)
    public String getReleaseFullversion() {
        return this.releaseFullversion;
    }
    
    public void setReleaseFullversion(String releaseFullversion) {
        this.releaseFullversion = releaseFullversion;
    }
    
    @Column(name="release_memocode", nullable=false, length=300)
    public String getReleaseMemocode() {
        return this.releaseMemocode;
    }
    
    public void setReleaseMemocode(String releaseMemocode) {
        this.releaseMemocode = releaseMemocode;
    }
    
    @Column(name="database_version", nullable=false)
    public long getDatabaseVersion() {
        return this.databaseVersion;
    }
    
    public void setDatabaseVersion(long databaseVersion) {
        this.databaseVersion = databaseVersion;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="released_on", nullable=false, length=13)
    public Date getReleasedOn() {
        return this.releasedOn;
    }
    
    public void setReleasedOn(Date releasedOn) {
        this.releasedOn = releasedOn;
    }




}


