package WrenchDb.DAL.Entities;
// Generated 5-dic-2013 18.23.45 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.GenerationTime;

/**
 * WdbSettings generated by hbm2java
 */
@Entity
@Table(name="wdb_settings"
    ,schema="public"
)
public class WdbSettings  implements java.io.Serializable {


     private long settingId;
     private WdbApplication wdbApplication;
     private String settingValue;
     private String settingCategory;
     private String settingKey;

    public WdbSettings() {
    }

	
    public WdbSettings(long settingId, WdbApplication wdbApplication) {
        this.settingId = settingId;
        this.wdbApplication = wdbApplication;
    }
    public WdbSettings(long settingId, WdbApplication wdbApplication, String settingValue, String settingCategory, String settingKey) {
       this.settingId = settingId;
       this.wdbApplication = wdbApplication;
       this.settingValue = settingValue;
       this.settingCategory = settingCategory;
       this.settingKey = settingKey;
    }
   
     @Id 
      @Generated(GenerationTime.INSERT)
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="setting_id", unique=true, nullable=false)
    public long getSettingId() {
        return this.settingId;
    }
    
    public void setSettingId(long settingId) {
        this.settingId = settingId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="application_id", nullable=false)
    public WdbApplication getWdbApplication() {
        return this.wdbApplication;
    }
    
    public void setWdbApplication(WdbApplication wdbApplication) {
        this.wdbApplication = wdbApplication;
    }
    
    @Column(name="setting_value", length=2000)
    public String getSettingValue() {
        return this.settingValue;
    }
    
    public void setSettingValue(String settingValue) {
        this.settingValue = settingValue;
    }
    
    @Column(name="setting_category", length=244)
    public String getSettingCategory() {
        return this.settingCategory;
    }
    
    public void setSettingCategory(String settingCategory) {
        this.settingCategory = settingCategory;
    }
    
    @Column(name="setting_key", length=240)
    public String getSettingKey() {
        return this.settingKey;
    }
    
    public void setSettingKey(String settingKey) {
        this.settingKey = settingKey;
    }




}


