echo ###########################
echo "build empty war"
echo "###########################"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
call ant BuildEmptyWar
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
echo "###########################"
echo "build ca war"
echo "###########################"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
call ant BuildCAWar

echo "###########################"
echo "build ca war"
echo "###########################"
echo "#"
echo "#"
echo "#"
echo "#"
echo "#"
call ant BuildProjectTemplate