package WrenchDb.DAL.Test;
// Generated 26-nov-2013 23.03.15 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * WdbApplication generated by hbm2java
 */
public class WdbApplication  implements java.io.Serializable {


     private long applicationId;
     private String applicationName;
     private String applicationHostname;
     private Set<WdbSettings> wdbSettingses = new HashSet<WdbSettings>(0);
     private Set<WdbChangescript> wdbChangescripts = new HashSet<WdbChangescript>(0);
     private Set<WdbSitemap> wdbSitemaps = new HashSet<WdbSitemap>(0);
     private Set<WdbEntity> wdbEntities = new HashSet<WdbEntity>(0);

    public WdbApplication() {
    }

	
    public WdbApplication(long applicationId, String applicationName) {
        this.applicationId = applicationId;
        this.applicationName = applicationName;
    }
    public WdbApplication(long applicationId, String applicationName, String applicationHostname, Set<WdbSettings> wdbSettingses, Set<WdbChangescript> wdbChangescripts, Set<WdbSitemap> wdbSitemaps, Set<WdbEntity> wdbEntities) {
       this.applicationId = applicationId;
       this.applicationName = applicationName;
       this.applicationHostname = applicationHostname;
       this.wdbSettingses = wdbSettingses;
       this.wdbChangescripts = wdbChangescripts;
       this.wdbSitemaps = wdbSitemaps;
       this.wdbEntities = wdbEntities;
    }
   
    public long getApplicationId() {
        return this.applicationId;
    }
    
    public void setApplicationId(long applicationId) {
        this.applicationId = applicationId;
    }
    public String getApplicationName() {
        return this.applicationName;
    }
    
    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }
    public String getApplicationHostname() {
        return this.applicationHostname;
    }
    
    public void setApplicationHostname(String applicationHostname) {
        this.applicationHostname = applicationHostname;
    }
    public Set<WdbSettings> getWdbSettingses() {
        return this.wdbSettingses;
    }
    
    public void setWdbSettingses(Set<WdbSettings> wdbSettingses) {
        this.wdbSettingses = wdbSettingses;
    }
    public Set<WdbChangescript> getWdbChangescripts() {
        return this.wdbChangescripts;
    }
    
    public void setWdbChangescripts(Set<WdbChangescript> wdbChangescripts) {
        this.wdbChangescripts = wdbChangescripts;
    }
    public Set<WdbSitemap> getWdbSitemaps() {
        return this.wdbSitemaps;
    }
    
    public void setWdbSitemaps(Set<WdbSitemap> wdbSitemaps) {
        this.wdbSitemaps = wdbSitemaps;
    }
    public Set<WdbEntity> getWdbEntities() {
        return this.wdbEntities;
    }
    
    public void setWdbEntities(Set<WdbEntity> wdbEntities) {
        this.wdbEntities = wdbEntities;
    }




}


