package WrenchDb.DAL.Test;
// Generated 26-nov-2013 23.03.15 by Hibernate Tools 3.2.1.GA



/**
 * WdbEntity generated by hbm2java
 */
public class WdbEntity  implements java.io.Serializable {


     private long entityId;
     private WdbApplication wdbApplication;
     private String entityName;
     private String entityDesc;
     private Boolean isManaged;

    public WdbEntity() {
    }

	
    public WdbEntity(long entityId, WdbApplication wdbApplication, String entityName) {
        this.entityId = entityId;
        this.wdbApplication = wdbApplication;
        this.entityName = entityName;
    }
    public WdbEntity(long entityId, WdbApplication wdbApplication, String entityName, String entityDesc, Boolean isManaged) {
       this.entityId = entityId;
       this.wdbApplication = wdbApplication;
       this.entityName = entityName;
       this.entityDesc = entityDesc;
       this.isManaged = isManaged;
    }
   
    public long getEntityId() {
        return this.entityId;
    }
    
    public void setEntityId(long entityId) {
        this.entityId = entityId;
    }
    public WdbApplication getWdbApplication() {
        return this.wdbApplication;
    }
    
    public void setWdbApplication(WdbApplication wdbApplication) {
        this.wdbApplication = wdbApplication;
    }
    public String getEntityName() {
        return this.entityName;
    }
    
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }
    public String getEntityDesc() {
        return this.entityDesc;
    }
    
    public void setEntityDesc(String entityDesc) {
        this.entityDesc = entityDesc;
    }
    public Boolean getIsManaged() {
        return this.isManaged;
    }
    
    public void setIsManaged(Boolean isManaged) {
        this.isManaged = isManaged;
    }




}


