package WrenchDb.DAL.Test;
// Generated 26-nov-2013 23.03.15 by Hibernate Tools 3.2.1.GA



/**
 * WdbSettings generated by hbm2java
 */
public class WdbSettings  implements java.io.Serializable {


     private long settingId;
     private WdbApplication wdbApplication;
     private String settingValue;
     private String settingCategory;
     private String settingKey;

    public WdbSettings() {
    }

	
    public WdbSettings(long settingId, WdbApplication wdbApplication) {
        this.settingId = settingId;
        this.wdbApplication = wdbApplication;
    }
    public WdbSettings(long settingId, WdbApplication wdbApplication, String settingValue, String settingCategory, String settingKey) {
       this.settingId = settingId;
       this.wdbApplication = wdbApplication;
       this.settingValue = settingValue;
       this.settingCategory = settingCategory;
       this.settingKey = settingKey;
    }
   
    public long getSettingId() {
        return this.settingId;
    }
    
    public void setSettingId(long settingId) {
        this.settingId = settingId;
    }
    public WdbApplication getWdbApplication() {
        return this.wdbApplication;
    }
    
    public void setWdbApplication(WdbApplication wdbApplication) {
        this.wdbApplication = wdbApplication;
    }
    public String getSettingValue() {
        return this.settingValue;
    }
    
    public void setSettingValue(String settingValue) {
        this.settingValue = settingValue;
    }
    public String getSettingCategory() {
        return this.settingCategory;
    }
    
    public void setSettingCategory(String settingCategory) {
        this.settingCategory = settingCategory;
    }
    public String getSettingKey() {
        return this.settingKey;
    }
    
    public void setSettingKey(String settingKey) {
        this.settingKey = settingKey;
    }




}


